# Generate the contents for upload to a test bucket.
# library(calcite); source("setup-private.R"); 
# source("fresh-upload.R")

# Base persistent upload, for reliable testing.
tmp <- tempfile()
dir.create(tmp)

# Saving multiple objects to a directory.
df <- exampleObject()
saveObject(df, tmp, "my_first_df")

library(scRNAseq)
sce <- ZeiselBrainData()
assay(sce) <- as(assay(sce), "dgCMatrix")
sce <- annotateObject(sce,
    title="Zeisel mouse brain scRNA-seq",
    description="scRNA-seq data for 3000 cells in the mouse brain, generated by Zeisel et al. (2015) using the Fluidigm C1 technology.",
    maintainers="Aaron Lun <infinite.monkeys.with.keyboards@gmail.com>",
    species=10090,
    genome=list(list(id="mm10", source="UCSC")),
    origin=list(list(source="PubMed", id="25700174"), list(source="GEO", id="GSE60361"))
)
saveObject(sce, tmp, "my_first_sce")

# Uploading it to the backend (requires authentication):
uploadDirectory(tmp, "test", "v1")
